app = "your-app-name"
primary_region = "your-preferred-region"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  FLASK_APP = "app.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static" 