app = "your-app-name"
primary_region = "your-preferred-region"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  FLASK_APP = "wsgi.py"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static" 